#!groovy

// Generated by IBM TransformationAdvisor
// Wed May 01 17:45:24 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}